// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyILKpDbW6wdzYPpgXz1PnR-bi7T9Os10',
    appId: '1:950547134959:web:2de4b4a71c6dbe1bfa5e1a',
    messagingSenderId: '950547134959',
    projectId: 'proyectofinal-4b756',
    authDomain: 'proyectofinal-4b756.firebaseapp.com',
    storageBucket: 'proyectofinal-4b756.appspot.com',
    measurementId: 'G-ZDDMRLXZQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPw8ptJXwRXPXx1KVD812H7TdULBFY2aQ',
    appId: '1:950547134959:android:a5c43f7c8e647e22fa5e1a',
    messagingSenderId: '950547134959',
    projectId: 'proyectofinal-4b756',
    storageBucket: 'proyectofinal-4b756.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd7cX4FAczaP8xRSFi7P7-tVocHr1wboU',
    appId: '1:950547134959:ios:3c7ce7ae101d38c2fa5e1a',
    messagingSenderId: '950547134959',
    projectId: 'proyectofinal-4b756',
    storageBucket: 'proyectofinal-4b756.appspot.com',
    iosClientId: '950547134959-6lh2nodlfgtshlfuk28ha7klmqd2jin5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd7cX4FAczaP8xRSFi7P7-tVocHr1wboU',
    appId: '1:950547134959:ios:3c7ce7ae101d38c2fa5e1a',
    messagingSenderId: '950547134959',
    projectId: 'proyectofinal-4b756',
    storageBucket: 'proyectofinal-4b756.appspot.com',
    iosClientId: '950547134959-6lh2nodlfgtshlfuk28ha7klmqd2jin5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
